backend:
  name: git-gateway
  repo: Chef123454/forma-hospitality-
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
# force rebuild 2
